
    create table SAMPLE.ADDRESS (
        ID bigint generated by default as identity,
        CREATED timestamp not null,
        CREATED_BY varchar(255) not null,
        LAST_MODIFIED timestamp not null,
        LAST_MODIFIED_BY varchar(255) not null,
        UUID varchar(255) not null unique,
        VERSION integer,
        CITY varchar(16) not null,
        STREET varchar(16) not null,
        ZIP_CODE varchar(255),
        COUNTRY varchar(255) not null,
        STATE varchar(255) not null,
        primary key (ID),
        unique (UUID)
    );

    create table SAMPLE.COUNTRY (
        ID varchar(255) not null,
        NAME varchar(255),
        primary key (ID)
    );

    create table SAMPLE.PERSON (
        ID bigint generated by default as identity,
        CREATED timestamp not null,
        CREATED_BY varchar(255) not null,
        LAST_MODIFIED timestamp not null,
        LAST_MODIFIED_BY varchar(255) not null,
        UUID varchar(255) not null unique,
        VERSION integer,
        BIRTH_DATE date,
        FIRST_NAME varchar(16) not null,
        LAST_NAME varchar(16) not null,
        SOCIAL_SECURITY_NUMBER varchar(9),
        ADDRESS bigint,
        primary key (ID),
        unique (UUID)
    );

    create table SAMPLE.STATE (
        ID varchar(255) not null,
        NAME varchar(255),
        COUNTRY varchar(255) not null,
        primary key (ID)
    );

    create index IDX_ADDRESS_COUNTRY on SAMPLE.ADDRESS (COUNTRY);

    create index IDX_ADDRESS_STATE on SAMPLE.ADDRESS (STATE);

    alter table SAMPLE.ADDRESS 
        add constraint FK_ADDRESS_STATE 
        foreign key (STATE) 
        references SAMPLE.STATE;

    alter table SAMPLE.ADDRESS 
        add constraint FK_ADDRESS_COUNTRY 
        foreign key (COUNTRY) 
        references SAMPLE.COUNTRY;

    create index IDX_PERSON_ADDRESS on SAMPLE.PERSON (ADDRESS);

    alter table SAMPLE.PERSON 
        add constraint FK_PERSON_ADDRESS 
        foreign key (ADDRESS) 
        references SAMPLE.ADDRESS;

    create index IDX_STATE_COUNTRY on SAMPLE.STATE (COUNTRY);

    alter table SAMPLE.STATE 
        add constraint FK_STATE_COUNTRY 
        foreign key (COUNTRY) 
        references SAMPLE.COUNTRY;
